---
language: python
python:
  - "3.6"
services: docker

install:
  - pip install pipenv
  - pipenv install

script:
  - pipenv run molecule test

notifications:
webhooks: https://galaxy.ansible.com/api/v1/notifications/
