---
- name: Install MariaDB-backup
  yum:
    name: MariaDB-backup
    state: present
  become: true

- name: Create mariabackup user
  user:
    name: "{{ mariabackup_user }}"
    state: present
  become: true
