---
- name: Install MariaDB-backup
  yum:
    name: MariaDB-backup
    state: present
  become: true

- name: Create mariabackup user
  user:
    name: "{{ mariabackup_user }}"
    group: mysql
    state: present
  become: true

- name: Adjust permissions on mysql data folder
  file:
    path: /var/lib/mysql
    state: directory
    owner: mysql
    group: mysql
    mode: 0775
    recurse: true
  become: true

- name: Create mariabackup my.cnf file
  template:
    src: my.cnf.j2
    dest: /home/{{ mariabackup_user }}/.my.cnf
    owner: "{{ mariabackup_user }}"
    group: "{{ mariabackup_user }}"
    mode: 0600
  become: true
