---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: centos7
    image: geerlingguy/docker-centos7-ansible:latest
    pull: true
    pre_build_image: true
    privileged: true
    command: "/usr/sbin/init"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible
  inventory:
    host_vars:
      centos7:
        mariabackup_user: mariabackup
        mariabackup_mysql_user: root
        mariabackup_mysql_password: ""
  config_options:
    ssh_connection:
      pipelining: true
  lint:
    name: ansible-lint

scenario:
  name: default

verifier:
  name: testinfra
  options:
    n: auto
  lint:
    name: flake8
