---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: centos7
    image: geerlingguy/docker-centos7-ansible:latest
    pull: true
    pre_build_image: false
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    instances:
      - name: mariadb-backup-centos7

provisioner:
  name: ansible
  lint:
    name: ansible-lint

scenario:
  name: default

verifier:
  name: testinfra
  lint:
    name: flake8
